# Generated by Django 5.2 on 2025-04-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[(1, 'medico'), (2, 'psicologo'), (3, 'oftamologista')], max_length=55)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[(1, 'agendado'), (2, 'realizado'), (3, 'cancelado')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
