# Generated by Django 5.2 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.IntegerField(choices=[(3, 'cancelado'), (1, 'agendado'), (2, 'realizado')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.IntegerField(choices=[(1, 'medico'), (3, 'oftamologista'), (2, 'psicologo')]),
        ),
    ]
