# Generated by Django 5.2 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_consulta_status_alter_medico_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.IntegerField(choices=[(2, 'realizado'), (3, 'cancelado'), (1, 'agendado')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.IntegerField(choices=[(2, 'psicologo'), (3, 'oftamologista'), (1, 'medico')]),
        ),
    ]
